/**
 * server/services/customerAssistantService.ts
 *
 * WhatsApp Customer Assistant orchestration service.
 * - Authenticates customers by mapping verified WhatsApp phone numbers to Voltrix customerId
 * - Classifies natural language requests into structured intents (via Gemini / regex parser)
 * - Guarantees ZERO raw database queries are generated by the LLM
 * - Reuses OrderService, InquiryService, LogisticsService, PaymentService, DocumentService
 * - Formats concise WhatsApp-friendly responses
 */

import { db, ensureDb, isMongoReady, getMongoDb } from '@/lib/db';
import { normalizePhoneNumber } from '@/lib/phone';
import { ai } from '@/lib/ai';
import { WhatsAppService } from './whatsAppService';
import { OrderService } from './orderService';
import { InquiryService } from './inquiryService';
import { LogisticsService } from './logisticsService';
import { PaymentService } from './paymentService';
import { DocumentService } from './documentService';
import type { Customer, Dealer } from '@/types';

// Rate limiter & Message Deduplication state
const phoneRateLimits = new Map<string, { count: number; resetTime: number }>();
const processedMessageIds = new Set<string>();

// Periodic cleanup of rate limiter & deduplication cache (every 5 mins)
setInterval(() => {
    const now = Date.now();
    for (const [phone, record] of phoneRateLimits.entries()) {
        if (now > record.resetTime) {
            phoneRateLimits.delete(phone);
        }
    }
    if (processedMessageIds.size > 2000) {
        processedMessageIds.clear();
    }
}, 5 * 60 * 1000);

export type CustomerAssistantIntent =
    | 'GET_ORDER_COUNT'
    | 'LIST_ORDERS'
    | 'GET_LATEST_ORDER'
    | 'GET_LOGISTICS_STATUS'
    | 'LIST_INQUIRIES'
    | 'GET_INVOICE_DOCUMENT'
    | 'CONTACT_SUPPORT'
    | 'GENERAL_QUERY';

export interface ParsedIntentResult {
    intent: CustomerAssistantIntent;
    orderId?: string;
    topic?: string;
}

export class CustomerAssistantService {
    /**
     * Resolves an authorized Voltrix dealer by their registered phone number.
     * Matches primary phone, altPhone, and whatsappPhone.
     */
    public static async findDealerByPhone(rawPhone: string): Promise<Dealer | null> {
        await ensureDb();
        const cleanPhone = normalizePhoneNumber(rawPhone);
        if (!cleanPhone) return null;

        const last10 = cleanPhone.slice(-10);

        // 1. Search in-memory db
        if (db.dealers && Array.isArray(db.dealers)) {
            const found = db.dealers.find((d: any) => {
                const p1 = d.phone ? normalizePhoneNumber(d.phone) : '';
                const p2 = d.altPhone ? normalizePhoneNumber(d.altPhone) : '';
                const p3 = d.whatsappPhone ? normalizePhoneNumber(d.whatsappPhone) : '';
                const p4 = d.mobile ? normalizePhoneNumber(d.mobile) : '';
                return (
                    (p1 && p1.endsWith(last10)) ||
                    (p2 && p2.endsWith(last10)) ||
                    (p3 && p3.endsWith(last10)) ||
                    (p4 && p4.endsWith(last10))
                );
            });
            if (found) return found;
        }

        // 2. Search MongoDB if active
        if (isMongoReady()) {
            const mongoDb = getMongoDb();
            try {
                const regex = new RegExp(last10);
                const doc = await mongoDb.collection('dealers').findOne({
                    $or: [
                        { phone: regex },
                        { altPhone: regex },
                        { whatsappPhone: regex },
                        { mobile: regex }
                    ]
                });
                if (doc) {
                    return { ...doc, id: doc._id?.toString() || doc.id };
                }
            } catch (err) {
                console.error('[CustomerAssistantService] Error querying dealer by phone:', err);
            }
        }

        return null;
    }

    /**
     * Resolves an authenticated Voltrix customer by their verified WhatsApp sender phone.
     * Prevents data exposure if the number is unverified.
     */
    public static async findCustomerByVerifiedPhone(rawPhone: string): Promise<Customer | null> {
        await ensureDb();
        const cleanPhone = normalizePhoneNumber(rawPhone);
        if (!cleanPhone) return null;

        const last10 = cleanPhone.slice(-10);

        // 1. Search in-memory db
        if (db.customers && Array.isArray(db.customers)) {
            const found = db.customers.find((c: any) => {
                if (!c.phone) return false;
                const custNorm = normalizePhoneNumber(c.phone);
                return custNorm.endsWith(last10);
            });
            if (found) return found;
        }

        // 2. Search MongoDB if active
        if (isMongoReady()) {
            const mongoDb = getMongoDb();
            try {
                const regex = new RegExp(last10);
                const doc = await mongoDb.collection('customers').findOne({ phone: regex });
                if (doc) {
                    return { ...doc, id: doc._id?.toString() || doc.id };
                }
            } catch (err) {
                console.error('[CustomerAssistantService] Error querying customer by phone:', err);
            }
        }

        return null;
    }

    /**
     * Enforces rate limiting per WhatsApp phone number (max 10 messages/minute).
     */
    private static isRateLimited(cleanPhone: string): boolean {
        const now = Date.now();
        const windowMs = 60 * 1000;
        const maxPerWindow = 10;

        const record = phoneRateLimits.get(cleanPhone);
        if (!record || now > record.resetTime) {
            phoneRateLimits.set(cleanPhone, { count: 1, resetTime: now + windowMs });
            return false;
        }

        record.count++;
        return record.count > maxPerWindow;
    }

    /**
     * Classifies natural language queries into safe, structured intents.
     * ZERO raw database code or queries are generated.
     */
    public static async classifyIntent(text: string): Promise<ParsedIntentResult> {
        const clean = text.toLowerCase().trim();

        // 1. Fast deterministic regex matching
        if (
            clean.includes('how many order') ||
            clean.includes('order count') ||
            clean.includes('number of order') ||
            clean.includes('total order')
        ) {
            return { intent: 'GET_ORDER_COUNT' };
        }

        if (
            clean.includes('show my order') ||
            clean.includes('show orders') ||
            clean.includes('list my order') ||
            clean.includes('list orders') ||
            clean.includes('view my order') ||
            clean.includes('my orders') ||
            clean.includes('purchase history')
        ) {
            return { intent: 'LIST_ORDERS' };
        }

        if (
            clean.includes('where is my latest order') ||
            clean.includes('latest order') ||
            clean.includes('last order') ||
            clean.includes('where is my order') ||
            clean.includes('track order')
        ) {
            return { intent: 'GET_LATEST_ORDER' };
        }

        if (
            clean.includes('logistics') ||
            clean.includes('shipment') ||
            clean.includes('shipping') ||
            clean.includes('delivery status') ||
            clean.includes('dispatch') ||
            clean.includes('where is it')
        ) {
            return { intent: 'GET_LOGISTICS_STATUS' };
        }

        if (
            clean.includes('show my inquiries') ||
            clean.includes('show inquiries') ||
            clean.includes('my inquiries') ||
            clean.includes('inquiry status') ||
            clean.includes('support ticket') ||
            clean.includes('service request')
        ) {
            return { intent: 'LIST_INQUIRIES' };
        }

        if (
            clean.includes('invoice') ||
            clean.includes('send my invoice') ||
            clean.includes('send invoice') ||
            clean.includes('bill') ||
            clean.includes('receipt') ||
            clean.includes('document') ||
            clean.includes('download invoice')
        ) {
            return { intent: 'GET_INVOICE_DOCUMENT' };
        }

        if (
            !clean.includes('warranty') &&
            !clean.includes('guarantee') &&
            (clean.includes('contact support') ||
                clean.includes('customer support') ||
                clean.includes('talk to support') ||
                clean.includes('call support') ||
                clean.includes('human') ||
                clean.includes('talk to agent') ||
                clean.includes('help desk') ||
                clean.includes('phone number') ||
                clean.includes('representative'))
        ) {
            return { intent: 'CONTACT_SUPPORT' };
        }

        // 2. Gemini AI Structured Intent Classification if available
        if (ai && process.env.GEMINI_API_KEY) {
            try {
                const prompt = `Classify this customer WhatsApp message into exactly one of these intents:
- GET_ORDER_COUNT (e.g. "how many orders do I have?")
- LIST_ORDERS (e.g. "show my orders", "what did I buy?")
- GET_LATEST_ORDER (e.g. "where is my latest order?", "status of my recent purchase")
- GET_LOGISTICS_STATUS (e.g. "what's my logistics/order status?", "has my unit dispatched?")
- LIST_INQUIRIES (e.g. "show my inquiries", "check my request status")
- GET_INVOICE_DOCUMENT (e.g. "send my invoice/document", "need the bill")
- CONTACT_SUPPORT (e.g. "talk to agent", "customer service")
- GENERAL_QUERY (general power equipment inquiries or greetings)

Message: "${text}"

Respond with ONLY valid JSON: {"intent": "THE_INTENT", "orderId": "optional_id_or_empty"}`;

                const response = await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt,
                    config: {
                        temperature: 0.1,
                        responseMimeType: 'application/json',
                    },
                });

                const contentText = response.text?.trim() || '';
                const parsed = JSON.parse(contentText);
                if (parsed.intent) {
                    return {
                        intent: parsed.intent as CustomerAssistantIntent,
                        orderId: parsed.orderId || undefined,
                    };
                }
            } catch (aiErr) {
                console.warn('[CustomerAssistantService] AI intent classification fallback:', aiErr);
            }
        }

        return { intent: 'GENERAL_QUERY' };
    }

    /**
     * Primary handler for incoming WhatsApp webhook messages.
     */
    public static async handleIncomingMessage({
        from,
        messageId,
        text,
    }: {
        from: string;
        messageId: string;
        text: string;
    }): Promise<{ success: boolean; replyText?: string }> {
        // 1. Deduplicate webhook delivery
        if (messageId) {
            if (processedMessageIds.has(messageId)) {
                console.log(`[CustomerAssistantService] Deduplicating already-processed message: ${messageId}`);
                return { success: true };
            }
            processedMessageIds.add(messageId);
        }

        // Mark as read in WhatsApp
        if (messageId) {
            WhatsAppService.markMessageAsRead(messageId).catch(() => {});
        }

        const cleanPhone = normalizePhoneNumber(from);

        // 2. Enforce Rate Limiting
        if (this.isRateLimited(cleanPhone)) {
            const limitMsg = `⚠️ *Notice:* You have sent multiple requests in a short period. Please wait a minute before messaging again.`;
            await WhatsAppService.sendTextMessage(from, limitMsg);
            return { success: true, replyText: limitMsg };
        }

        // 3. FIRST CHECK: Is the sender an authorized or registered Dealer?
        const dealer = await this.findDealerByPhone(from);
        if (dealer) {
            const dealerName = dealer.companyName || dealer.name || 'Valued Partner';
            const isApproved = dealer.status === 'approved';

            const dealerMsg =
                `👋 *Hello ${dealerName}!* ⚡\n\n` +
                `We identified your WhatsApp number as a registered Voltrix Dealer Partner.\n\n` +
                `🤖 *Dealer AI Assistant:* Dedicated commercial and engineering tools—including our AI Load Calculator, custom B2B proposal generator, margin estimator, and technical sizing—are exclusively available for you inside the *Dealers Portal*.\n\n` +
                `👉 *Please access the AI in your Dealer Portal:*\n` +
                `🔗 https://voltrixpower.com/#dealer-portal\n\n` +
                (isApproved
                    ? `Please log in to your portal and open the *Dealer AI Assistant* tab to calculate sizing, generate proposals, or analyze customer requirements.`
                    : `_Note: Your dealer application is currently pending admin review. Once approved, you will have full access to the Dealer AI tools._`) +
                `\n\nFor administrative desk queries, call our operations team at *+91 90323 72136*.`;

            await WhatsAppService.sendTextMessage(from, dealerMsg);
            return { success: true, replyText: dealerMsg };
        }

        // 4. SECOND CHECK: Is the sender a Verified Customer?
        const customer = await this.findCustomerByVerifiedPhone(from);

        // If neither a dealer nor a verified customer, protect confidential data
        if (!customer) {
            const guestMsg =
                `⚡ *Welcome to Voltrix Power Systems!* ⚡\n\n` +
                `We could not locate an active Voltrix customer account registered with this WhatsApp number (+${cleanPhone}).\n\n` +
                `🔒 *Security Notice:* Confidential order details, delivery tracking, and official invoices are strictly protected and only accessible from verified customer phone numbers.\n\n` +
                `*How can we assist you?*\n` +
                `• *Products:* Ask about our Servo Stabilizers (1–2500 kVA), Online UPS (1–500 kVA), Inverters & Solar Solutions.\n` +
                `• *Get a Quotation / Support:* Contact our sales team at *voltrixpowersystems@gmail.com* or call *+91 90323 72136*.\n` +
                `• *Dealers:* If you are a dealer applying to join, apply at https://voltrixpower.com/#dealer-register.`;

            await WhatsAppService.sendTextMessage(from, guestMsg);
            return { success: true, replyText: guestMsg };
        }

        // 5. User is a VERIFIED CUSTOMER -> Answer queries and give information/results!
        const customerId = customer.id;
        const customerName = customer.name || 'Valued Customer';

        // Classify Intent
        const parsed = await this.classifyIntent(text);
        let replyText = '';

        switch (parsed.intent) {
            case 'GET_ORDER_COUNT': {
                const count = await OrderService.getOrderCount(customerId);
                replyText =
                    `📦 *Your Voltrix Orders Summary*\n\n` +
                    `Hello *${customerName}*,\n` +
                    `You currently have *${count}* registered order${count === 1 ? '' : 's'} with Voltrix Power Systems.\n\n` +
                    (count > 0
                        ? `Type *"Show my orders"* to view your recent purchases or *"Where is my latest order?"* for delivery status.`
                        : `You have no completed purchases yet. If you recently placed an inquiry, type *"Show my inquiries"* to check its progress.`);
                break;
            }

            case 'LIST_ORDERS': {
                const orders = await OrderService.getOrders(customerId, 4);
                if (orders.length === 0) {
                    replyText =
                        `📦 *Your Orders*\n\n` +
                        `Hello *${customerName}*, no orders were found under your account.\n` +
                        `Type *"Show my inquiries"* to check quotation requests in progress.`;
                } else {
                    replyText = `📦 *Your Recent Orders (Total: ${orders.length})*\n\n`;
                    orders.forEach((o, idx) => {
                        const dateStr = o.closedAt || o.createdAt ? new Date(o.closedAt || o.createdAt).toLocaleDateString('en-IN') : 'Recent';
                        const amountStr = o.closedAmount ? `₹${o.closedAmount.toLocaleString('en-IN')}` : 'N/A';
                        const statusTag = o.dealStatus === 'closed' ? '✅ Delivered' : (o.paymentStatus === 'paid' ? '🚚 Dispatched' : '⏳ In Discussion');
                        replyText +=
                            `*${idx + 1}. ${o.productTitle || o.productCategory || 'Equipment'}*\n` +
                            `• Order ID: \`${o.id}\`\n` +
                            `• Date: ${dateStr}\n` +
                            `• Value: ${amountStr}\n` +
                            `• Status: ${statusTag}\n\n`;
                    });
                    replyText += `Reply with *"Where is my latest order?"* or *"Send my invoice"* for more details.`;
                }
                break;
            }

            case 'GET_LATEST_ORDER': {
                const order = await OrderService.getLatestOrder(customerId);
                if (!order) {
                    replyText =
                        `📦 *Latest Order Status*\n\n` +
                        `Hello *${customerName}*, you do not have any active orders on record.\n` +
                        `To place a new order or check an inquiry, please contact our sales team at *+91 90323 72136*.`;
                } else {
                    const logistics = await LogisticsService.getOrderLogisticsStatus(customerId, order.id);
                    const dateStr = order.closedAt || order.createdAt ? new Date(order.closedAt || order.createdAt).toLocaleDateString('en-IN') : 'Recent';
                    const amountStr = order.closedAmount ? `₹${order.closedAmount.toLocaleString('en-IN')}` : 'N/A';

                    replyText =
                        `⚡ *Latest Order Update*\n\n` +
                        `• *Product:* ${order.productTitle || order.productCategory || 'Power Equipment'}\n` +
                        `• *Order ID:* \`${order.id}\`\n` +
                        `• *Date:* ${dateStr}\n` +
                        `• *Amount:* ${amountStr}\n` +
                        `• *Status:* *${logistics?.status || 'Processing'}*\n` +
                        `• *Logistics Note:* ${logistics?.details || 'Being prepared by fulfillment team.'}\n\n` +
                        (logistics?.dealerName ? `• *Authorized Partner:* ${logistics.dealerName}\n` : '') +
                        (logistics?.dealerContact ? `• *Partner Phone:* ${logistics.dealerContact}\n\n` : '\n') +
                        `Type *"Send my invoice"* to receive your official invoice PDF.`;
                }
                break;
            }

            case 'GET_LOGISTICS_STATUS': {
                const logistics = await LogisticsService.getOrderLogisticsStatus(customerId);
                if (!logistics) {
                    replyText =
                        `🚚 *Logistics & Tracking Status*\n\n` +
                        `Hello *${customerName}*, there are no active shipments linked to your account.\n` +
                        `For support, call us at *+91 90323 72136*.`;
                } else {
                    replyText =
                        `🚚 *Logistics & Delivery Status*\n\n` +
                        `• *Unit:* ${logistics.productTitle}\n` +
                        `• *Order ID:* \`${logistics.orderId}\`\n` +
                        `• *Status:* *${logistics.status}*\n` +
                        `• *Details:* ${logistics.details}\n` +
                        (logistics.dealerName ? `• *Dispatch Partner:* ${logistics.dealerName}\n` : '') +
                        (logistics.dealerContact ? `• *Partner Contact:* ${logistics.dealerContact}\n` : '') +
                        `\nNeed installation assistance? Reply *"Contact support"*.`;
                }
                break;
            }

            case 'LIST_INQUIRIES': {
                const inqs = await InquiryService.getCustomerInquiries(customerId, 4);
                if (inqs.length === 0) {
                    replyText =
                        `📋 *Your Inquiries*\n\n` +
                        `Hello *${customerName}*, you have no logged inquiries or quote requests.\n` +
                        `To submit a specification or request a quotation, reply with your requirements or visit https://voltrixpower.com.`;
                } else {
                    replyText = `📋 *Your Inquiries & Requests (Total: ${inqs.length})*\n\n`;
                    inqs.forEach((i, idx) => {
                        const dateStr = i.createdAt ? new Date(i.createdAt).toLocaleDateString('en-IN') : 'Recent';
                        const statusFormatted = (i.status || 'new').toUpperCase();
                        replyText +=
                            `*${idx + 1}. ${i.subject || 'Power Solution Inquiry'}*\n` +
                            `• Product: ${i.productInterest || 'General'}\n` +
                            `• Date: ${dateStr}\n` +
                            `• Status: *${statusFormatted}*\n\n`;
                    });
                    replyText += `An engineering advisor is assigned to active inquiries. Reply *"Contact support"* to speak with our team.`;
                }
                break;
            }

            case 'GET_INVOICE_DOCUMENT': {
                const doc = await DocumentService.getLatestInvoice(customerId);
                if (!doc) {
                    replyText =
                        `📄 *Invoice Document*\n\n` +
                        `Hello *${customerName}*, no invoice documents are currently available for your account.\n` +
                        `Once an order is confirmed, invoices are generated automatically.`;
                } else {
                    replyText =
                        `📄 *Invoice Details*\n\n` +
                        `• *Invoice No:* *${doc.invoiceNumber}*\n` +
                        `• *Product:* ${doc.productTitle}\n` +
                        `• *Amount:* ₹${doc.amount.toLocaleString('en-IN')}\n` +
                        `• *Date:* ${new Date(doc.date).toLocaleDateString('en-IN')}\n\n`;

                    if (doc.documentUrl) {
                        // Send actual document file via WhatsApp Cloud API
                        await WhatsAppService.sendDocumentMessage(
                            from,
                            doc.documentUrl,
                            doc.filename,
                            `Invoice ${doc.invoiceNumber} - Voltrix Power Systems`
                        );
                        replyText += `✅ *Your official invoice document has been sent above.*`;
                    } else {
                        replyText +=
                            `The PDF file is being prepared by our billing department.\n` +
                            `For immediate assistance, email *voltrixpowersystems@gmail.com* quoting Invoice No *${doc.invoiceNumber}*.`;
                    }
                }
                break;
            }

            case 'CONTACT_SUPPORT': {
                replyText =
                    `📞 *Voltrix Customer Support*\n\n` +
                    `We are here to assist you!\n\n` +
                    `• *Direct Helpline:* +91 90323 72136 | +91 73867 10160\n` +
                    `• *Email:* voltrixpowersystems@gmail.com\n` +
                    `• *Working Hours:* Mon - Sat, 9:00 AM - 7:00 PM IST\n` +
                    `• *Corporate Address:* Gandi Maisamma X Road, Hyderabad - 500043\n\n` +
                    `Feel free to reply anytime with *"Show my orders"*, *"Where is my latest order?"*, or *"Show my inquiries"*.`;
                break;
            }

            case 'GENERAL_QUERY':
            default: {
                // Verified customer asks a general or product question: give them full answers
                replyText = await this.answerCustomerGeneralQuery(customer, text);
                break;
            }
        }

        await WhatsAppService.sendTextMessage(from, replyText);
        return { success: true, replyText };
    }

    /**
     * Answers product questions, technical sizing, warranty, or company queries for verified customers.
     */
    public static async answerCustomerGeneralQuery(customer: Customer, text: string): Promise<string> {
        const clean = text.toLowerCase().trim();
        const customerName = customer.name || 'Valued Customer';

        // 1. Simple greetings
        if (/^(hi|hello|hey|namaste|greetings|start|menu|help)$/i.test(clean)) {
            return (
                `⚡ *Hello ${customerName}! Welcome to Voltrix Power Systems.* ⚡\n\n` +
                `Your WhatsApp number is verified with your customer account.\n\n` +
                `*How can I assist you today?*\n` +
                `• *Ask any question:* e.g. _"What servo stabilizer do I need for a 15 HP motor?"_ or _"Tell me about online UPS warranty"_\n` +
                `• *Orders:* Type *"Show my orders"* or *"Where is my latest order?"*\n` +
                `• *Invoices:* Type *"Send my invoice"*\n` +
                `• *Inquiries:* Type *"Show my inquiries"*\n` +
                `• *Support:* Type *"Contact support"*`
            );
        }

        // 2. If Gemini AI is configured, generate an intelligent answer
        if (ai && process.env.GEMINI_API_KEY) {
            try {
                const prompt = `You are the official Voltrix Power Systems WhatsApp Customer Assistant.
Voltrix Power Systems is a premier manufacturer of industrial power conditioning equipment located in Hyderabad, India.
Customer Name: ${customerName} (Verified Customer)

PRODUCT & TECHNICAL KNOWLEDGE:
1. Servo Voltage Stabilizers:
   - Air-Cooled (1 kVA – 100 kVA): Single & 3-Phase, ±1% output regulation, digital microcontroller, high efficiency (>98%). Ideal for CNC, printing, elevators, residential, hospitals.
   - Oil-Cooled (15 kVA – 2500 kVA): Heavy-duty 3-Phase balanced & unbalanced. Copper wound, transformer oil cooling, withstands extreme voltage fluctuations (e.g. 300V–470V or 340V–480V).
2. Online UPS Systems:
   - True Double Conversion Online UPS: 1 kVA – 500 kVA (1-Phase & 3-Phase). Zero transfer time, IGBT inverter, DSP control, pure sine wave.
3. Isolation & Ultra-Isolation Transformers:
   - 1 kVA – 500 kVA, noise attenuation > 120 dB, eliminates harmonics & ground noise.
4. Solar Power Solutions:
   - On-Grid, Off-Grid, and Hybrid Solar Inverters and Rooftop Plants.
5. Warranty & Service Support:
   - Standard 1-3 years warranty, on-site service, 24/7 technical assistance across India.
   - Contact: +91 90323 72136 | +91 73867 10160 | voltrixpowersystems@gmail.com
   - Works: Gandi Maisamma X Road, Hyderabad - 500043.

GUIDELINES:
- Provide a direct, professional, and clear answer to the customer's question.
- Format for WhatsApp (*bold*, _italics_, bullet points).
- Keep length concise (under 200 words).
- Conclude with a helpful next step.

Customer Question: "${text}"`;

                const response = await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt,
                    config: {
                        temperature: 0.2,
                    },
                });

                const reply = response.text?.trim();
                if (reply) {
                    return reply;
                }
            } catch (err) {
                console.warn('[CustomerAssistantService] Gemini AI general query error, falling back:', err);
            }
        }

        // 3. Fallback knowledge answer
        return this.getFallbackKnowledgeAnswer(customer, text);
    }

    /**
     * Fallback structured technical knowledge answers for verified customers.
     */
    private static getFallbackKnowledgeAnswer(customer: Customer, text: string): string {
        const clean = text.toLowerCase();
        const customerName = customer.name || 'Valued Customer';

        if (clean.includes('stabilizer') || clean.includes('servo') || clean.includes('voltage')) {
            return (
                `⚡ *Voltrix Servo Voltage Stabilizers*\n\n` +
                `Hello *${customerName}*,\n` +
                `Voltrix manufactures high-precision digital Servo Stabilizers with ±1% voltage accuracy and >98% efficiency:\n\n` +
                `• *Air-Cooled:* 1 kVA to 100 kVA (Single & 3-Phase) for commercial & light industrial equipment.\n` +
                `• *Oil-Cooled:* 15 kVA to 2500 kVA (3-Phase) for heavy factories, CNC machines, and hospitals.\n` +
                `• *Protection:* High/low voltage cut-off, overload, single-phasing, and surge suppression.\n\n` +
                `To calculate capacity sizing for your machines or request a quotation, call our engineering desk at *+91 90323 72136*.`
            );
        }

        if (clean.includes('ups') || clean.includes('power backup') || clean.includes('online ups')) {
            return (
                `🔋 *Voltrix Online UPS Systems*\n\n` +
                `Hello *${customerName}*,\n` +
                `Our Online UPS solutions feature True Double Conversion with zero transfer time:\n\n` +
                `• *Capacity:* 1 kVA to 500 kVA (1-Phase & 3-Phase)\n` +
                `• *Technology:* High-frequency IGBT PWM Inverter with advanced DSP micro-controller.\n` +
                `• *Applications:* Data centers, IT infrastructure, diagnostic imaging, and process automation.\n\n` +
                `For backup duration and battery sizing, contact our team at *+91 90323 72136*.`
            );
        }

        if (clean.includes('solar') || clean.includes('panel') || clean.includes('inverter')) {
            return (
                `☀️ *Voltrix Solar Power Solutions*\n\n` +
                `Hello *${customerName}*,\n` +
                `Voltrix designs and commissions complete solar energy systems:\n\n` +
                `• *On-Grid Systems:* Reduce electricity bills with net-metering.\n` +
                `• *Off-Grid & Hybrid:* Uninterrupted solar power with intelligent battery storage.\n` +
                `• *Solar Inverters:* High efficiency MPPT solar power conditioning units.\n\n` +
                `To schedule a solar site feasibility audit, contact *+91 90323 72136*.`
            );
        }

        if (clean.includes('warranty') || clean.includes('guarantee') || clean.includes('service') || clean.includes('repair') || clean.includes('amc')) {
            return (
                `🛡️ *Warranty & Service Support*\n\n` +
                `Hello *${customerName}*,\n` +
                `All Voltrix power products come with standard manufacturer warranty (1 to 3 years depending on unit model) and on-site support.\n\n` +
                `• *Helpline:* +91 90323 72136 | +91 73867 10160\n` +
                `• *Email:* voltrixpowersystems@gmail.com\n` +
                `• *AMC Plans:* Comprehensive Annual Maintenance Contracts are available for continuous uptime.\n\n` +
                `Reply *"Contact support"* to connect with an engineer.`
            );
        }

        if (clean.includes('price') || clean.includes('cost') || clean.includes('rate') || clean.includes('quote') || clean.includes('quotation')) {
            return (
                `💰 *Pricing & Quotations*\n\n` +
                `Hello *${customerName}*,\n` +
                `Voltrix provides custom factory-direct pricing based on exact equipment specifications, input voltage range, and cooling requirements.\n\n` +
                `To receive a detailed commercial quotation with technical datasheet:\n` +
                `• Visit: https://voltrixpower.com/#contact\n` +
                `• Call: *+91 90323 72136*\n` +
                `• Email: *voltrixpowersystems@gmail.com*`
            );
        }

        // Generic informative response
        return (
            `⚡ *Voltrix Power Systems Assistant*\n\n` +
            `Hello *${customerName}*,\n` +
            `Thank you for reaching out to Voltrix Power Systems. We manufacture Servo Stabilizers (1–2500 kVA), Online UPS (1–500 kVA), Isolation Transformers, and Solar Solutions.\n\n` +
            `*Quick Actions:*\n` +
            `• *"Show my orders"* — View recent orders\n` +
            `• *"Where is my latest order?"* — Check tracking\n` +
            `• *"Send my invoice"* — Get invoice copy\n` +
            `• *"Show my inquiries"* — View requests\n` +
            `• *"Contact support"* — Talk to our team\n\n` +
            `Or simply ask any product or technical question!`
        );
    }
}
